name: CI
on: [push, pull_request]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - uses: rhysd/action-setup-vim@v1
      - run: cd ./test && bundle install --jobs=3 --retry=3
      - run: cd ./test && rake ci
        env:
          PROFILE_LOG: profile.txt
      - uses: actions/setup-python@v1
      - name: Install covimerage
        run: |
          pip install covimerage
          covimerage --version
      - name: Run covimerage
        run: cd ./test && covimerage write_coverage profile.txt
      - name: Take coverage
        run: |
          cd ./test
          coverage report
          coverage xml
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./test/coverage.xml

  vint:
    name: Run vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install vim-vint
      - run: vint --warning --verbose --enable-neovim ./autoload ./plugin
